# Generated by Django 6.0 on 2025-12-27 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('VOLUNTEER', 'Volunteer'), ('ORG', 'Organization'), ('ADMIN', 'Admin')], default='VOLUNTEER', max_length=20),
        ),
    ]
