# Generated by Django 5.2.8 on 2026-01-05 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_username_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerprofile',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
