# Generated by Django 5.2.8 on 2026-01-10 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_volunteerprofile_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerprofile',
            name='reliability_score',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
    ]
