# Generated by Django 5.2.8 on 2026-01-10 15:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_volunteerprofile_reliability_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerprofile',
            name='reliability_score',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
