# Generated by Django 5.2.8 on 2026-01-06 18:32

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='eventsignup',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='event',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='event',
            name='end_at',
        ),
        migrations.RemoveField(
            model_name='event',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_at',
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(default='אחר', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.date(2025, 1, 1)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='needed_volunteers',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.TimeField(default=datetime.time(9, 0)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='event',
            name='organization',
            field=models.ForeignKey(limit_choices_to={'role': 'ORG'}, on_delete=django.db.models.deletion.CASCADE, related_name='events_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eventsignup',
            name='volunteer',
            field=models.ForeignKey(limit_choices_to={'role': 'VOLUNTEER'}, on_delete=django.db.models.deletion.CASCADE, related_name='event_signups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='eventsignup',
            constraint=models.UniqueConstraint(fields=('event', 'volunteer'), name='unique_volunteer_per_event'),
        ),
    ]
