# Generated by Django 5.2.8 on 2026-01-10 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsignup',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
