---
deployment:
  tasks:
    - export DEPLOYPATH=/home/$USER/apps/voluntrack/
    - /bin/mkdir -p $DEPLOYPATH

    - /bin/cp -R backend $DEPLOYPATH
    - /bin/cp -R core $DEPLOYPATH
    - /bin/cp manage.py $DEPLOYPATH
    - /bin/cp -n requirements.txt $DEPLOYPATH || true