---
deployment:
  tasks:
    - export DEPLOYPATH=/home/leviid/public_html/voluntrack
    - /bin/mkdir -p $DEPLOYPATH

    # build React (Vite) מתוך התיקייה frontend
    - cd /home/<CPANEL_USER>/repositories/VolunTrack/frontend
    - /usr/bin/npm ci || /usr/bin/npm install
    - /usr/bin/npm run build

    # לפרוס את התוצר ל-public_html
    - /bin/rm -rf $DEPLOYPATH/*
    - /bin/cp -R dist/* $DEPLOYPATH/
