# Generated by Django 5.2.8 on 2026-01-10 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationcampaign',
            name='event',
        ),
        migrations.AddField(
            model_name='donation',
            name='donor_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='donation',
            name='donor_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='donation',
            name='organization',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'ORG'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donations_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='donationcampaign',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='donation',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='donation',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='donations.donationcampaign'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donor_name',
            field=models.CharField(blank=True, default='אנונימי', max_length=200),
        ),
        migrations.AlterField(
            model_name='donationcampaign',
            name='goal_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='donationcampaign',
            name='organization',
            field=models.ForeignKey(limit_choices_to={'role': 'ORG'}, on_delete=django.db.models.deletion.CASCADE, related_name='donation_campaigns', to=settings.AUTH_USER_MODEL),
        ),
    ]
